CREATE TABLE IF NOT EXISTS tags (
	id SERIAL PRIMARY KEY,

	name VARCHAR(72) NOT NULL UNIQUE,
	description TEXT DEFAULT NULL,
	color VARCHAR(12) DEFAULT NULL, -- hex color code
	collection_id INT NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
	created_by INT NOT NULL REFERENCES users(id) ON DELETE NO ACTION,

	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

